In [12]:
#Generate random decimals for the eight products to represent the historical returns for the last ten years
import random
ram={}
for j in range(1,9):
    ram[j] = []
    for i in range(10):
        num = random.random()
        ram[j].append(num)
print(ram)

{1: [0.730644309697101, 0.933310813088036, 0.8278515213850972, 0.5570087028422696, 0.06033844426242929, 0.649585378629887, 0.0959206941128119, 0.43190850923904, 0.2310821212416011, 0.20686804031932204], 2: [0.4655329947806024, 0.833042995136155, 0.06195705012502173, 0.9864623132298175, 0.7033367861531431, 0.32998663601996425, 0.7623897069299833, 0.4621775256536248, 0.3553967771353391, 0.3771724973325207], 3: [0.29816935080572926, 0.2545840235362409, 0.009497662095408477, 0.42870853066199666, 0.02717998732296567, 0.03442935011938608, 0.8698038430628857, 0.02103402320004144, 0.664553227938657, 0.5171194614233185], 4: [0.42982431531439513, 0.07138563174697976, 0.6550692114575521, 0.6625260615190491, 0.6479623242945328, 0.4627787248939328, 0.24015952258188522, 0.47375546771650756, 0.8844306623383169, 0.8405548384179897], 5: [0.31583364534328773, 0.9213954131855603, 0.6989090662377647, 0.4394564133774763, 0.9275161451138859, 0.9566906684125887, 0.8101419449511987, 0.9263346338372813, 0.3779317067197179, 0.9711632702432182], 6: [0.7967764573544805, 0.710558910410261, 0.1254588061734817, 0.3511994076919588, 0.6808070945132283, 0.5888623635893572, 0.49204676009529147, 0.3710504527934192, 0.6686268445405504, 0.9920103592464804], 7: [0.6854511334119615, 0.7429858546425435, 0.883666044129265, 0.6384285605334513, 0.754772596981366, 0.9742018841875256, 0.15227317782784122, 0.4696313078278005, 0.6289851470884907, 0.5246029933990406], 8: [0.5963145352875697, 0.8474457367498468, 0.0432841615874876, 0.5674365210138189, 0.04758484812824926, 0.088260997711881, 0.24662418766953942, 0.6264497695475388, 0.5155940631403853, 0.21226962389586834]}

In [13]:
p1 = ram[1]
p2=ram[2]
p3=ram[3]
p4=ram[4]
p5=ram[5]
p6=ram[6]
p7=ram[7]
p8=ram[8]

In [14]:
lispro = [p1,p2,p3,p4,p5,p6,p7,p8]

In [15]:
#Store those data into a csv file
import csv
header = [i for i in range(1,11)]

In [16]:
with open('Historical returns.csv','w', encoding='UTF8', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(header)
    for i in range(8):
        writer.writerow(lispro[i])

In [17]:
import pandas as pd
from scipy.optimize import minimize

In [18]:
df = pd.read_csv("Historical returns.csv")
df = df.transpose()
df

,0,1,2,3,4,5,6,7
1,0.730644,0.465533,0.298169,0.429824,0.315834,0.796776,0.685451,0.596315
2,0.933311,0.833043,0.254584,0.071386,0.921395,0.710559,0.742986,0.847446
3,0.827852,0.061957,0.009498,0.655069,0.698909,0.125459,0.883666,0.043284
4,0.557009,0.986462,0.428709,0.662526,0.439456,0.351199,0.638429,0.567437
5,0.060338,0.703337,0.027180,0.647962,0.927516,0.680807,0.754773,0.047585
6,0.649585,0.329987,0.034429,0.462779,0.956691,0.588862,0.974202,0.088261
7,0.095921,0.762390,0.869804,0.240160,0.810142,0.492047,0.152273,0.246624
8,0.431909,0.462178,0.021034,0.473755,0.926335,0.371050,0.469631,0.626450
9,0.231082,0.355397,0.664553,0.884431,0.377932,0.668627,0.628985,0.515594
10,0.206868,0.377172,0.517119,0.840555,0.971163,0.992010,0.524603,0.212270

In [19]:
cov_matrix=df.cov().copy()
cov_matrix

,0,1,2,3,4,5,6,7
0,0.098438,-0.012624,-0.044141,-0.033189,-0.012533,-0.021550,0.042380,0.033869
1,-0.012624,0.078419,0.026771,-0.029980,-0.001635,0.007219,-0.023986,0.036209
2,-0.044141,0.026771,0.092106,0.003747,-0.026227,0.021848,-0.050662,0.015206
3,-0.033189,-0.029980,0.003747,0.064530,-0.018343,0.004366,0.008932,-0.028011
4,-0.012533,-0.001635,-0.026227,-0.018343,0.067869,0.006436,-0.000504,-0.025151
5,-0.021550,0.007219,0.021848,0.004366,0.006436,0.062465,-0.004719,0.009458
6,0.042380,-0.023986,-0.050662,0.008932,-0.000504,-0.004719,0.052994,-0.013227
7,0.033869,0.036209,0.015206,-0.028011,-0.025151,0.009458,-0.013227,0.081606

In [20]:
ER = [0.04,0.07,0.18,0.06,0.07,0.17,0.29,0.48]

In [21]:
n=len(df.columns)
#Assume the minimum expected return that the portfolio much achieve is e_0
e_0 = 0.015
#define objective function
def risk(w):
    risk_sum=0
    for i in range(n):
        for j in range(n):
            risk_sum +=w[i]*w[j]*cov_matrix.iloc[i,j]
    return risk_sum
#define minimum expected return inequality constraint
def constraint1(w):
    return sum([w[i]*ER[i] for i in range(n)])-e_0
#define weights sum up to 1 equality constraint
def constraint2(w):
    return sum([w[i] for i in range(n)])-1.0
#define the customer preference constraints
def constraint3(w):
    return w[0]+w[5]-0.3
def constraint4(w):
    return -w[6]-w[7]+0.15
def constraint5(w):
    return w[3]+w[5]-w[2]-w[6]

con1={'type':'ineq','fun':constraint1}
con2={'type':'eq','fun':constraint2}
con3={'type':'ineq','fun':constraint3}
con4={'type':'ineq','fun':constraint4}
con5={'type':'ineq','fun':constraint5}
cons=([con1,con2,con3,con4,con5])

#define bounds
b=(0,1)
bnds=(b,)*n

#define inital values for weights
w0=[0.2]*n

solution=minimize(risk,w0,method='SLSQP',bounds=bnds,constraints=cons)

In [22]:
solution

 message: Optimization terminated successfully
 success: True
  status: 0
     fun: 0.0027616147398290803
       x: [ 2.432e-01  1.141e-01  1.387e-01  2.528e-01  1.944e-01
            5.678e-02  2.246e-18  1.247e-18]
     nit: 16
     jac: [ 8.659e-03  4.206e-03  4.363e-03  4.048e-03  4.096e-03
            9.028e-03  4.875e-03  6.089e-03]
    nfev: 144
    njev: 16

In [23]:
solution.fun

0.0027616147398290803

In [24]:
solution_list =solution.x.tolist()
#print(solution_list)
stocks=list(df)
print(stocks)
solution_df=pd.DataFrame(solution_list,index =stocks,columns = ['weight'])
solution_df
#solution_df.sum()
solution_df.transpose()

[0, 1, 2, 3, 4, 5, 6, 7]

,0,1,2,3,4,5,6,7
weight,0.243219,0.114116,0.13867,0.252836,0.194378,0.056781,2.246331e-18,1.246832e-18